const {app,BrowserWindow}=require('electron'),assert=require('assert/strict'),fs=require('fs');
app.whenReady().then(async()=>{let w;try{
 fs.mkdirSync('test-output',{recursive:true});w=new BrowserWindow({width:1400,height:1000,show:true,webPreferences:{contextIsolation:true}});await w.loadFile('REKHTA.html');const run=s=>w.webContents.executeJavaScript(s);
 await run(`(()=>{rkWelcomeStart.click();newDoc(false);language.value='ur';window.a=createText(700,60,false);a.innerHTML='<span style="color:red">FIRST</span><br><b>SECOND</b><br>THIRD';window.b=createText(700,300,false);b.textContent='OTHER';selectObj(a,false);a.focus();const r=document.createRange();r.selectNodeContents(a.querySelector('b'));getSelection().removeAllRanges();getSelection().addRange(r);document.dispatchEvent(new Event('selectionchange'));setAlign('center');})()`);
 assert.deepEqual(await run(`[...a.children].map(p=>p.style.textAlign)`),['right','center','right']);assert.equal(await run(`getComputedStyle(a.querySelector('span[style*="red"]')).color`),'rgb(255, 0, 0)');assert.equal(await run(`b.style.textAlign`),'start');assert.equal(await run(`a.dir`),'rtl');
 await run(`(()=>{const p=a.children[0],r=document.createRange();r.selectNodeContents(p);r.collapse(true);getSelection().removeAllRanges();getSelection().addRange(r);a.focus();document.dispatchEvent(new Event('selectionchange'));setAlign('left');})()`);assert.deepEqual(await run(`[...a.children].map(p=>p.style.textAlign)`),['left','center','right']);
 await run(`(()=>{const r=document.createRange();r.selectNodeContents(a.children[2]);r.collapse(false);getSelection().removeAllRanges();getSelection().addRange(r);a.focus();})()`);w.webContents.sendInputEvent({type:'keyDown',keyCode:'R',modifiers:['control']});w.webContents.sendInputEvent({type:'keyUp',keyCode:'R',modifiers:['control']});await new Promise(r=>setTimeout(r,100));assert.deepEqual(await run(`[...a.children].map(p=>p.style.textAlign)`),['left','center','right']);assert.equal(await run(`a.children.length`),3);
 await run(`window.saved=serialize();restore(saved);window.a=[...page.querySelectorAll('.textobj')].find(e=>e.textContent==='FIRSTSECONDTHIRD');`);assert.deepEqual(await run(`[...a.querySelectorAll(':scope > [data-rekhta-paragraph]')].map(p=>p.style.textAlign)`),['left','center','right']);
 // Selected span across two paragraphs changes only those paragraphs and retains inline styles.
 await run(`(()=>{selectObj(a,false);a.focus();const r=document.createRange();r.setStart(a.children[0],0);r.setEnd(a.children[2],0);getSelection().removeAllRanges();getSelection().addRange(r);setAlign('center');})()`);assert.deepEqual(await run(`[...a.children].map(p=>p.style.textAlign)`),['center','center','right']);assert.equal(await run(`a.querySelector('b').textContent`),'SECOND');
 // Empty and nested paragraphs must not duplicate on repeated alignment.
 await run(`(()=>{a.innerHTML='<div><div>ONE</div></div><div><br></div><div>THREE</div>';a.focus();const r=document.createRange();r.selectNodeContents(a);getSelection().removeAllRanges();getSelection().addRange(r);setAlign('left');setAlign('right');})()`);assert.equal(await run(`a.children.length`),3);assert.equal(await run(`a.textContent`),'ONETHREE');
 await run(`(()=>{a.innerHTML='<div style="font-size:40px;color:blue">LARGE</div><div>SMALL</div>';a.focus();const r=document.createRange();r.selectNodeContents(a.children[0]);getSelection().removeAllRanges();getSelection().addRange(r);setAlign('center');})()`);assert.equal(await run(`getComputedStyle(a.children[0]).fontSize`),'40px');assert.equal(await run(`getComputedStyle(a.children[0]).color`),'rgb(0, 0, 255)');assert.equal(await run(`getComputedStyle(a.children[1]).fontSize`),'24px');
 fs.writeFileSync('test-output/alignment.png',(await w.webContents.capturePage()).toPNG());console.log('PASS: independent Left/Center/Right paragraphs, selected ranges, current-line caret, Ctrl+R, formatting/direction preserved, other object unchanged, Save/Open and empty/nested lines');app.exit(0);
 }catch(e){console.error(e);if(w)fs.writeFileSync('test-output/alignment-failure.png',(await w.webContents.capturePage()).toPNG());app.exit(1);}});
