const {app,BrowserWindow}=require('electron'),fs=require('fs'),assert=require('assert/strict'),path=require('path');let win;
app.whenReady().then(async()=>{try{
 fs.mkdirSync('test-output',{recursive:true});win=new BrowserWindow({width:1400,height:1000,show:true,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}});await win.loadFile(path.join(__dirname,'REKHTA.html'));const run=s=>win.webContents.executeJavaScript(s);await run(`(()=>{rkWelcome?.remove();startStudio('regular');page.innerHTML='';selectObj(null);language.value='en';window.t=createText(100,50,false);t.style.left='48px';t.style.width='600px';t.style.fontFamily='Times New Roman';t.style.fontSize='24px';t.innerHTML=Array.from({length:90},(_,i)=>'<span style="color:'+(i===45?'#ff0000':'#111111')+'">LINE '+i+' — English</span><br>').join('');t.focus();placeCaretEnd(t);})()`);await run(`document.fonts.ready.then(()=>{})`);await run(`rekhtaPagination.paginate(t)`);
 const initial=await run(`({pages:rekhtaPagination.count,frames:rekhtaPagination.frames.length,text:rekhtaPagination.frames.map(e=>e.textContent).join(''),active:document.activeElement.dataset.flowOrder,height:rekhtaPagination.height,total:page.offsetHeight})`);console.log('Automatic page flow',initial.pages,initial.frames,initial.active);assert(initial.pages>=3);assert.equal(initial.pages,initial.frames);for(let i=0;i<90;i++)assert(initial.text.includes('LINE '+i+' — English'));assert.equal(Number(initial.active),initial.frames-1,'Caret follows typing to last page');
 assert.equal(await run(`page.querySelectorAll('span[style*="ff0000"],span[style*="255, 0, 0"]').length>0`),true,'Inline colour preserved');
 await run(`window.saved=serialize();restore(saved);`);assert.equal(await run(`rekhtaPagination.count`),initial.pages);assert.equal(await run(`rekhtaPagination.frames.map(e=>e.textContent).join('')`),initial.text);
 await run(`(()=>{const first=rekhtaPagination.frames[0];rekhtaPagination.frames.slice(1).forEach(e=>e.remove());first.innerHTML='SHORT TEXT';first.focus();placeCaretEnd(first);rekhtaPagination.paginate(first);})()`);assert.equal(await run(`rekhtaPagination.count`),1,'Deleting text shrinks unused pages');
 await run(`restore(saved);snapshot();(()=>{const last=rekhtaPagination.frames.at(-1);last.focus();placeCaretEnd(last);insertRekhtaText(last,'\\nAFTER PAGE BREAK');})()`);await run(`Promise.resolve().then(()=>{})`);assert(await run(`rekhtaPagination.frames.map(e=>e.textContent).join('').includes('AFTER PAGE BREAK')`));await run(`snapshot();undo()`);assert(!(await run(`rekhtaPagination.frames.map(e=>e.textContent).join('').includes('AFTER PAGE BREAK')`)),'Undo restores document before last edit');await run(`redo()`);assert(await run(`rekhtaPagination.frames.map(e=>e.textContent).join('').includes('AFTER PAGE BREAK')`));
 // PDF export must contain the same number of physical sheets as the editor.
 await run(`(()=>{window.oldCapture=captureRekhtaCanvas;captureRekhtaCanvas=async(_source,o)=>{const c=document.createElement('canvas');c.width=Math.round(o.width);c.height=Math.round(o.height);const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,c.width,c.height);x.fillStyle='black';x.fillRect(50,50,20,20);return c;};window.oldSave=saveConfiguredExport;saveConfiguredExport=async(b,name)=>{window.savedExport={blob:b,name};};})()`);
 await run(`runConfiguredExport({format:'pdf',area:'page',name:'All Pages',dpi:72,scaling:100}).then(()=>{})`);const exportPdf=await run(`savedExport.blob.text()`);assert.equal((exportPdf.match(/\/Type \/Page\b/g)||[]).length,await run(`rekhtaPagination.count`));
 await run(`runConfiguredExport({format:'png',area:'page',name:'Images',dpi:72,scaling:100,from:2,to:3}).then(()=>{})`);assert.equal(await run(`savedExport.name`),'Images-pages.zip');const zip=await run(`savedExport.blob.arrayBuffer().then(b=>Array.from(new Uint8Array(b)))`);fs.writeFileSync('test-output/paginated-images.zip',Buffer.from(zip));assert(Buffer.from(zip).includes(Buffer.from('Images-page-2.png'))&&Buffer.from(zip).includes(Buffer.from('Images-page-3.png')));
 await run(`captureRekhtaCanvas=oldCapture;saveConfiguredExport=oldSave;rekhtaPagination.preparePrint();void 0;`);const printed=await win.webContents.printToPDF({printBackground:true,preferCSSPageSize:true});fs.writeFileSync('test-output/paginated-print.pdf',printed);assert.equal((printed.toString('latin1').match(/\/Type \/Page\b/g)||[]).length,await run(`rekhtaPagination.count`),'Print has no blank first sheet and includes every page');
 await run(`(()=>{document.getElementById('rkPrintPages')?.remove();openExportDialog('pdf');})()`);assert.equal(Number(await run(`expTo.max`)),await run(`rekhtaPagination.count`));await run(`closeIpDialog()`);
 await run(`(()=>{page.innerHTML='';selectObj(null);language.value='ur';window.u=createText(700,48,false);u.style.left='48px';u.style.width='600px';u.innerHTML=Array.from({length:100},(_,i)=>'<div>السلام علیکم — '+i+'</div>').join('');u.focus();placeCaretEnd(u);rekhtaPagination.paginate(u);})()`);assert(await run(`rekhtaPagination.count>=3`),'Urdu flows to additional pages');const urdu=await run(`rekhtaPagination.frames.map(e=>e.textContent).join('')`);await run(`rekhtaPagination.paginate(rekhtaPagination.frames[0])`);assert.equal(await run(`rekhtaPagination.frames.map(e=>e.textContent).join('')`),urdu,'Reflow preserves pasted block paragraphs');assert(await run(`rekhtaPagination.frames.every(e=>e.dir==='rtl'&&e.style.fontFamily.includes('Jameel'))`));fs.writeFileSync('test-output/pagination-workspace.png',(await win.webContents.capturePage()).toPNG());
 console.log('PASS: English/Urdu automatic pages, caret, formatting, shrink, save/open, undo/redo, PDF/PNG ranges and physical print sheets');app.exit(0);
 }catch(e){console.error(e);if(win)fs.writeFileSync('test-output/pagination-failure.png',(await win.webContents.capturePage()).toPNG());app.exit(1);}});
